// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:326127882154:web:7cb9104a9d2ec822d665d3',
    messagingSenderId: '326127882154',
    projectId: 'instagram-clone-68853',
    authDomain: 'instagram-clone-68853.firebaseapp.com',
    storageBucket: 'instagram-clone-68853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',,
    appId: '1:326127882154:android:76a2c600f58ac8b3d665d3',
    messagingSenderId: '326127882154',
    projectId: 'instagram-clone-68853',
    storageBucket: 'instagram-clone-68853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:326127882154:ios:0c6addc5b5214fb3d665d3',
    messagingSenderId: '326127882154',
    projectId: 'instagram-clone-68853',
    storageBucket: 'instagram-clone-68853.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:326127882154:ios:0c6addc5b5214fb3d665d3',
    messagingSenderId: '326127882154',
    projectId: 'instagram-clone-68853',
    storageBucket: 'instagram-clone-68853.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:326127882154:web:462f4f6da0945690d665d3',
    messagingSenderId: '326127882154',
    projectId: 'instagram-clone-68853',
    authDomain: 'instagram-clone-68853.firebaseapp.com',
    storageBucket: 'instagram-clone-68853.firebasestorage.app',
  );

}
